// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// jtag_xfer //
// --------- //

#define jtag_xfer_wrap_target 0
#define jtag_xfer_wrap 7
#define jtag_xfer_pio_version 0

static const uint16_t jtag_xfer_program_instructions[] = {
            //     .wrap_target
    0x90a0, //  0: pull   block           side 0
    0xb027, //  1: mov    x, osr          side 0
    0x90a0, //  2: pull   block           side 0
    0x7001, //  3: out    pins, 1         side 0
    0xb842, //  4: nop                    side 1
    0x5801, //  5: in     pins, 1         side 1
    0x1043, //  6: jmp    x--, 3          side 0
    0x9020, //  7: push   block           side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program jtag_xfer_program = {
    .instructions = jtag_xfer_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = jtag_xfer_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config jtag_xfer_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + jtag_xfer_wrap_target, offset + jtag_xfer_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

